baseURL = "http://hassomepicklejuice.github.io/"
languageCode = "en-us"
title = "Hassomepicklejuice"

theme = "PaperMod"

[params]
defaultTheme = "auto"
ShowToc = true

[params.homeInfoParams]
Title = "Hasse"
Content = """
`pronouns = [("she", "her", "her"), ("they", "them", "their")]`

i sometimes do programming :3
"""

[[params.socialIcons]]
name = "github"
url = "https://github.com/hassomepicklejuice"

[[params.socialIcons]]
name = "tumblr"
url = "https://hassomepicklejuice.tumblr.com/"
